---
title: "GGC Alcohol Harms Report"
output: 
  flexdashboard::flex_dashboard:
    logo: ../phs_logo_mono.png
    orientation: rows
    vertical_layout: fill
    css: www/css_styles.css
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(openxlsx)
library(tidyverse)
library(knitr)
library(reactable)
library(sparklines)
library(phsstyles)
library(plotly)
library(stringr)
library(crosstalk)
library(DT)
library(sjmisc)
library(downloadthis)
```

```{r init, include=FALSE}
source("process_wrangle.R")
source("table_output_profile.R")

data_dir <- "/conf/LIST_analytics/Glasgow City/Drugs & Alcohol/Alcohol/output/"
data <-  read.xlsx(paste0(data_dir, "GGC Alcohol Data.xlsx"), 1) %>% 
  select(-lookup)


data <- data %>% process_year()
#selecting the rows in the right order
data <- data[c("iz", "iz_name", "year_start", "year_str", "hscp", "indicator", "pop", "number", "rate")]

big_areas <- c("Scotland", "NHS Greater Glasgow and Clyde", "NHS GGC")
```

Notes {data-icon="fa-info-circle"}
=====================================

row {.tabset}
--------------------------------------------------

### General Notes

#### **Alcohol Harms Report**
#### **NHS Greater Glasgow and Clyde**
##### Report date: `r format(Sys.time(), "%d %b %Y")`

<br/>

The tables in the **Profile** page shows information at interzone level for various alcohol related harms indicators.

(1) **Alcohol Specific Deaths:** the time periods for this indicator are 3 calendar year aggregates.
(2) **Alcohol-related mental health admissions:** the time periods for this indicator are 3 financial year aggregates.
(3) **Alcohol-related hospital admissions:** the time periods for this indicator are single financial years.  

<br/>

#### <span style="text-decoration:underline">**Data Notes**</span>

**Alcohol-related hospital admissions**  
Source: SMR01, Public Health Scotland

(1) The number of inpatient and day case stays where an alcohol-related condition is recorded in any of the 6 diagnostic positions.
(2) Alcohol-related condition ICD-10 diagnosis codes: E24.4, E51.2, F10, G31.2, G62.1, G72.1, I42.6, K29.2, K70, K85.2, K86.0, O35.4, P04.3, Q86.0, R78.0, T51.0, T51.1, T51.9, X45, X65, Y15, Y57.3, Y90, Y91, Z50.2, Z71.4, Z72.1.
(3) Includes both elective and non-elective admissions.


**Alcohol-related mental health admissions**  
Source: SMR04, Public Health Scotland

(1) The number of psychiatric inpatient and day case stays where an alcohol-related condition is recorded in any of the 6 diagnostic positions.
(2) Alcohol-related condition ICD-10 diagnosis codes: E24.4, E51.2, F10, G31.2, G62.1, G72.1, I42.6, K29.2, K70, K85.2, K86.0, O35.4, P04.3, Q86.0, R78.0, T51.0, T51.1, T51.9, X45, X65, Y15, Y57.3, Y90, Y91, Z50.2, Z71.4, Z72.1.


**Alcohol-specific deaths**  
Source: Deaths, National Records Scotland

(1) The number of deaths where the underlying cause of death is related to alcohol consumption.
(2) Underlying cause of death ICD-10 codes: E24.4, F10, G31.2, G62.1, G72.1, I42.6, K29.2, K70, K85.2, K86.0, Q86.0, R78.0, X45, X65, Y15

<br/>




<style>
div.phsblu50 { background-color:#E9D8D8; border-radius: 5px; padding: 20px; color: #A32E14}
</style>
<div class = "phsblu50">
Management Information only, not for onward distribution
This information has been released for management information purposes only. The data have not been adjusted to protect against potential disclosure risks and may contain information which enables (perhaps with the aid of further knowledge of the topic) an individual patient to be identified. Please ensure circulation is restricted and that patient confidentiality is not compromised. For further guidance see NSS’s Statistical Disclosure Control Protocol http://www.isdscotland.org/Products-and-Services/Data-Protection-and-Confidentiality/#smallNumbers. Please contact phs.list.glasgow@nhs.net if you have any queries regarding this.
</div>



### Profile Notes {data-icon="fa-table"}

#### **Alcohol Harms Report**
#### **NHS Greater Glasgow and Clyde**
#### Information for using the profile page

<br/>

The profile page is intended to give an overview of the alcohol related harms indicators for HSCPs and Interzones (IZs).  
The two tables under the tabs **HSCP profile** and **IZ Profile** show EASR rates (per 10,000 population) for the indicators and the respective rate of change of those indicators compared to the previous period.

<br/>

##### **HSCP Profile**

This table shows rates and rates of change of indicators for the HSCPs within NHS GGC and for NHS GGC and Scotland as a whole.

- Click the download button to export the data shown in **HSCP Profile** as an excel table.
- The table will include red circles \ <span style="color: #B8100D"> `r shiny::icon("circle")` </span> \ next to data that signify if that HSCP is in the 75^th^ percentile or above for all NHS GGC HSCPs

<br/>


##### **IZ Profile**

This table shows rates and rates of change of indicators for all IZs within NHS GGC.

- Use the HSCP selector at the top of the page or the search bars above the two leftmost columns to filter the data.
- Note that selecting **(All)** in the HSCP selector does not function as it should. To return to the unfiltered view, delete anything in the filter box using backspace.


Since there are many rows in **IZ Profile** the user is left to select which rows they wish to download. Downloading all rows is still possible.  

- Select a row using the tick-boxes on the left to add it to the rows for which you would like to download the displayed data.
- Initially all rows are selected and you cannot select zero rows.
- Change to the **Profile Download** tab to show all the rows that are to be downloaded and click on your selected format to start the download.
- The download data is in a wide format where the additional details are new columns in the data.  

Like with the **HSCP profile**, this profile also shows red circles to indicate rows in a high percentile of the data.   

- In the initial view there will be red circles \ <span style="color: #B8100D"> `r shiny::icon("circle")` </span> \ that signify if that value is in the 75^th^ percentile or above for all IZs in NHS GGC.
- Once the data is filtered, an open red circle \ <span style="color: #B8100D"> `r shiny::icon("circle-o")` </span> \ will also be shown to signify if that value is in the 75^th^ percentile or above for the filtered data. If you filter for a specific HSCP this will help identify outliers within that HSCP.

<br/>

**The following applies to both profile tables**

- Click on the column headers to sort by that column ascending and again to sort descending.  

- The value columns are coloured based on the relative values in that column:
    + <span class="larger_smaller_nums" style="background-color: #EAC43A">larger numbers</span> 
    + <span class="larger_smaller_nums" style="background-color: #FBF4DA">smaller numbers</span>
- The rate of change columns are coloured based on the relative positive (+ve) or negative (-ve) values in that column:
    + <span class="larger_smaller_nums" style="background-color: #d26146">large +ve change</span> 
    + <span class="larger_smaller_nums" style="background-color: #EFC6BD">small +ve change</span>
    + <span class="larger_smaller_nums" style="background-color: #DBECC1">small -ve change</span> 
    + <span class="larger_smaller_nums" style="background-color: #9CC951">large -ve change</span>
    + The rate of change columns also have arrows \ \ 
<span style="color: #B8100D"> `r shiny::icon("arrow-up")` </span> \ 
<span style="color: #71B109"> `r shiny::icon("arrow-down")` </span> \  
<span style="color: #F4E61F"> `r shiny::icon("grip-lines")` </span> \ \ 
corresponding to +ve, -ve and zero change.  
    + A dash -- in the rate of change column indicates that the previous value was zero so no relative change can be calculated.   



- Click on the black triangle at the start of each row to display more details
    - Comparisons in rates relative to Scotland and NHS GGC. The cells for this are coloured to the same scheme as the rate of change columns.
    - The most recent population of that intermediate zone.  








Profile {data-icon="fa-table"}
=====================================


```{r crosstalk_filter}
all_table_data <- make_profile_frame(data) %>% arrange(desc(across(contains("hospital admissions"))))

```


row {.tabset}
--------------------------------------------------
```{r profile_setup, include=FALSE}
iz_table <- iz_data(all_table_data)
big_area_table <- big_area_data(all_table_data) %>% arrange(iz %in% big_areas)

download_table_iz <- table_for_download(iz_table) %>% mutate_if(is.numeric, function(x) round(x, digits=2))

shared_table_iz_main <- SharedData$new(iz_table, group="profile_table", key = ~iz)
shared_table_iz_download <- SharedData$new(download_table_iz, group="profile_table", key = ~iz)
```

### HSCP Profile
```{r reactable_big_area_display_profile}
download_this(
    table_for_download(big_area_table),
    output_name = "Alcohol_harms_big_areas",
    output_extension = ".xlsx",
    button_label = "Download data as xlsx",
    button_type = "primary",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
profile_table(big_area_table, big_area_table, all_default_cols=FALSE)
```

### IZ Profile

```{r reactable_display_profile}
filter_select("auto", "HSCP", shared_table_iz_main, ~hscp, multiple=FALSE)
profile_table(iz_table, shared_table_iz_main)

```

### IZ profile download

```{r dt_download_profile}
datatable(shared_table_iz_download,
          height=0.5,
          rownames = FALSE,
          extensions = 'Buttons',
          class = "display",
          selection = "none",
          options=list(dom = 'Bfrtip',
                       buttons = c('copy', 'csv', 'excel'))
          )

```
