---
title: "GGC_qtr_report.rmd"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(knitr)
library(lubridate)
library(kableExtra)
library(phsstyles)
library(plotly)
library(DT)

data_dir <- "/conf/LIST_analytics/Glasgow City/Drugs & Alcohol/Alcohol/EASR/output/"
data <- read_csv(paste0(data_dir, "Qtr_alc_adm_GGC.csv")) %>% 
  select(-lookup) %>% 
  mutate(date_end = ymd(date_end),
         EASR=round(EASR, 2))
  

source("trend_table.R")
```

# Landing Page

# Tables

## row {.tabset}

### Alcohol Related Hospital Attendances

```{r tab_1_gen, fig.height=0.5, fig.width = 2.5, include=FALSE}
make_all_plots(data, "number", trend_table_data)
trend_table_data_1 <- trend_table_data(data, "number")
table_1 <- make_trend_table(trend_table_data_1)
```

```{r tab_1_show}
table_1
```

### Attendances EASR

```{r tab_2_gen, fig.height=0.5, fig.width = 2.5, include=FALSE}
make_all_plots(data, "EASR", trend_table_data)
trend_table_data_2 <- trend_table_data(data, "EASR")
table_2 <- make_trend_table(trend_table_data_2)
```

```{r tab_2_show}
table_2
```

## row

### EASR Trends in detail

```{r trends, show=FALSE}
colours <- c("purple",
             "magenta",
             "blue",
             "green",
             "graphite",
             "teal",
             "liberty",
             "rust")

colours <- phs_colours(sprintf("phs-%s", colours))

big_areas <- c("Scotland", "NHS Greater Glasgow and Clyde")
trend_data <- data %>%
  select(area, date_end, EASR) %>%
  arrange(area %in% big_areas, area) %>%
  rename(Area=area) %>% 
  pivot_wider(names_from = "Area", values_from = "EASR")

min_y <- trend_data %>% select(-date_end) %>% min()
max_y <- trend_data %>% select(-date_end) %>% max()
y_lower <- min_y - 0.1*(max_y-min_y)
y_upper <- max_y + 0.1*(max_y-min_y)

area_names <- trend_data %>% names() %>% tail(-1)
fig <- trend_data %>% 
  plot_ly(type = 'scatter', mode = 'lines',
          line=list(width=3.5)) %>% 
  layout(title = '',
         xaxis = list(title = ''),
         yaxis = list (title = 'Attendances EASR',
                       range = c(y_lower, y_upper)),
         hovermode = "x unified")


for (i in seq_along(area_names)){
  area <- area_names[[i]]
  trace_f <- as.formula(paste0("~`", area, "`"))
  if(area %in% big_areas){
    fig <- fig %>% add_trace(x=~date_end, y=trace_f, name=area, line=list(dash = 'dash', color=colours[[i]]))
  }else{
    fig <- fig %>% add_trace(x=~date_end, y=trace_f, name=area, visible="legendonly", line=list(color=colours[[i]]))  
  }

}
fig

```


# Change Trends

## row {.tabset}

### Attendance Changes

```{r tab_3_gen, fig.height=0.5, fig.width = 2.5, include=FALSE}
make_all_plots(data, "number", relative_change_table_data)
change_table_data_1 <- relative_change_table_data(data, "number")
table_3 <- make_relative_change_table(change_table_data_1)
```

```{r tab_3_show}
table_3
```

### EASR Changes

```{r tab_4_gen, fig.height=0.5, fig.width = 2.5, include=FALSE}
make_all_plots(data, "EASR", relative_change_table_data)
change_table_data_2 <- relative_change_table_data(data, "EASR")
table_4 <- make_relative_change_table(change_table_data_2)
```

```{r tab_4_show}
table_4
```

