---
title: "Reactable vs DT test"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(reactable)
library(crosstalk)
library(DT)
library(downloadthis)

knitr::opts_chunk$set(echo = TRUE)

make_p_m_color_pal <- function(plus_neg_zero_colours, bias = 1) {
  p_col <- plus_neg_zero_colours[[1]]
  n_col <- plus_neg_zero_colours[[2]]
  z_col <- plus_neg_zero_colours[[3]]
  
  get_colour_p <- colorRamp(c(z_col, p_col), bias = bias)
  get_colour_n <- colorRamp(c(z_col, n_col), bias = bias)
  
  function(x) {
    if (x==0){
      #usually white
      z_col
    } else if (x < 0){
      rgb(get_colour_n(abs(x)), maxColorValue = 255)
    } else {
      rgb(get_colour_p(x), maxColorValue = 255)
    }
  }
}

p_m_colours <- make_p_m_color_pal(c("#d26146", "#9cc951", "#ffffff"), bias=1.5)

```


## Display Table

```{r reactable, echo=FALSE}
cars_shared <- cars %>% SharedData$new()
reactable(
  cars_shared,
  selection = "multiple",
  defaultSelected = c(2),
  onClick = "select",
  rowStyle = list(cursor = "pointer"),
  minRows = 10,
  columns=list(
  speed=colDef(style = function(value){
    pos_max <- max(cars$speed)
    neg_max <- -1
    
    if (value==0 | is.na(value)){
      scaled <- 0
    } else if (value > 0){
      scaled <- value/pos_max
    } else {
      scaled <- value/neg_max
    }

    
    list(color = "#111", background = p_m_colours(scaled))
  })
  )
)
```

## Download Table

```{r DT, echo=FALSE}


datatable(cars_shared,
          height=0.5,
          extensions = 'Buttons',
          options=list(dom = 'tB',
                        buttons = c('copy', 'csv', 'excel')))
```