---
title: "GGC Alcohol Harms Report"
output: 
  flexdashboard::flex_dashboard:
    logo: ../phs_logo_mono.png
    orientation: rows
    vertical_layout: fill
    css: www/css_styles.css
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(openxlsx)
library(tidyverse)
library(knitr)
library(reactable)
library(sparklines)
library(phsstyles)
library(plotly)
library(stringr)
library(crosstalk)
library(DT)
library(sjmisc)
library(downloadthis)
library(here)
library(purrr)
```

```{r init, include=FALSE}
source(here("dashboard", "profile_report", "process_wrangle_profile.R"))
source(here("dashboard", "profile_report", "process_wrangle_indicator.R"))

source(here("dashboard", "profile_report", "table_output_profile.R"))
source(here("dashboard", "profile_report", "table_output_indicator.R"))

source(here("dashboard", "funcs_wrangle.R"))
source(here("dashboard", "funcs_dashboard.R"))

source(here("dashboard", "warning_text.R"))

# data_dir <- "/conf/LIST_analytics/Glasgow City/Drugs & Alcohol/Alcohol/output/"
# data <-  read.xlsx(paste0(data_dir, "GGC Alcohol Data.xlsx"), 1) %>% 
#   select(-lookup)


data <- read_csv(here("output", "profile_annual_data", "profile.csv")) %>% 
   select(-lookup)

# replace hscp with locality 
# we are mixing hscp and hscp_locality here because Glasgow City is too large.
# we split only that hscp in to its localities
data <- data %>% 
  mutate(hscp = hscp_locality) %>% 
  select(-hscp_locality)

data <- data %>% process_year()
#selecting the rows in the right order
data <- data[c("iz", "iz_name", "year_start", "year_str", "hscp", "indicator", "pop", "number", "rate")]

# Latest financial year (siunce "/"" is arranaged last) displayed in notes page
latest_year_str <- data %>% arrange(year_str) %>% pull(year_str) %>% unique %>% tail(1)

big_areas <- c("Scotland", "NHS Greater Glasgow and Clyde", "NHS GGC")


```

Notes {data-icon="fa-info-circle"}
=====================================

row {.tabset}
--------------------------------------------------

### General Notes

#### **Alcohol Harms Report**
#### **NHS Greater Glasgow and Clyde**
##### Time period: up to end of `r latest_year_str`
##### Report date: `r format(Sys.time(), "%d %b %Y")`

<div class = "warning_box">
Management Information only, not for onward distribution
This information has been released for management information purposes only. The data have not been adjusted to protect against potential disclosure risks and may contain information which enables (perhaps with the aid of further knowledge of the topic) an individual patient to be identified. Please ensure circulation is restricted and that patient confidentiality is not compromised. For further guidance see NSS’s Statistical Disclosure Control Protocol http://www.isdscotland.org/Products-and-Services/Data-Protection-and-Confidentiality/#smallNumbers. Please contact phs.list.glasgow@nhs.net if you have any queries regarding this.
</div>


<br/>


#### <span style="text-decoration:underline">**About**</span>
This dashboard provides information on various alcohol harms indicators at Intermediate Zone (IZ):

 - Alcohol-related hospital admissions 
 - Alcohol-related mental health admissions
 - Alcohol-specific deaths

All values shown are the **European Age-sex Standardised Rate (EASR) per 10,000 population**. Using this allows the comparison of areas with different age and sex distributions and also when the distribution changes over time.


<br/>


#### <span style="text-decoration:underline">**How to use**</span>
Select the buttons at the top of the dashboard to view the different pages available:

 - **Profile** – shows the latest data for each indicator (see ‘Profile Notes’ for more information).
 - **Hospital Admissions** – shows the trend in alcohol-related hospital admissions (see ‘Indicator Detail Notes’ for more information).
 - **Mental Health Admissions** – shows the trend in alcohol-related mental health admissions (see ‘Indicator Detail Notes’ for more information).
 - **Deaths** – shows the trend in alcohol-specific deaths (see ‘Indicator Detail Notes’ for more information).
 


<br/>




#### <span style="text-decoration:underline">**Data Notes**</span>

**Alcohol-related hospital admissions**  
Source: SMR01, Public Health Scotland

(1) The number of inpatient and day case stays where an alcohol-related condition is recorded in any of the 6 diagnostic positions.
(2) Alcohol-related condition ICD-10 diagnosis codes: E24.4, E51.2, F10, G31.2, G62.1, G72.1, I42.6, K29.2, K70, K85.2, K86.0, O35.4, P04.3, Q86.0, R78.0, T51.0, T51.1, T51.9, X45, X65, Y15, Y57.3, Y90, Y91, Z50.2, Z71.4, Z72.1.
(3) Includes both elective and non-elective admissions.
(4) The time periods are single financial years.


**Alcohol-related mental health admissions**  
Source: SMR04, Public Health Scotland

(1) The number of psychiatric inpatient and day case stays where an alcohol-related condition is recorded in any of the 6 diagnostic positions.
(2) Alcohol-related condition ICD-10 diagnosis codes: E24.4, E51.2, F10, G31.2, G62.1, G72.1, I42.6, K29.2, K70, K85.2, K86.0, O35.4, P04.3, Q86.0, R78.0, T51.0, T51.1, T51.9, X45, X65, Y15, Y57.3, Y90, Y91, Z50.2, Z71.4, Z72.1.
(3) The time periods are 3-year aggregate totals (financial years).


**Alcohol-specific deaths**  
Source: Deaths, National Records Scotland

(1) The number of deaths where the underlying cause of death is related to alcohol consumption.
(2) Underlying cause of death ICD-10 codes: E24.4, F10, G31.2, G62.1, G72.1, I42.6, K29.2, K70, K85.2, K86.0, Q86.0, R78.0, X45, X65, Y15
(3) The time periods are 3-year aggregate totals (calendar years).

<br/>



### Profile Notes

#### **Alcohol Harms Report**
#### **NHS Greater Glasgow and Clyde**
#### Information for using the profile page

<br/>

This page contains the alcohol harms profile by Intermediate Zone (IZ) and also by Health & Social Care Partnership (HSCP). Select the **IZ Profile** or **HSCP Profile** tab to view.

The profiles show the **European Age-sex Standardised Rate (EASR) per 10,000 population** for each indicator as well as the **rate of change (%)** compared to the previous time period.


<br/>


#### <span style="text-decoration:underline">**Overall**</span>

 - EASR cells are coloured light orange <span class="highlight_colour" style="background-color: #F3DE90">like this</span> to indicate values that are in the 75^th^ percentile or above for all NHS GGC.
 - Rate of change (% change) cells are coloured based on the relative positive (+ve) or negative (-ve) values in that column:
    + <span class="larger_smaller_nums" style="background-color: #d26146">large +ve change</span> 
    + <span class="larger_smaller_nums" style="background-color: #EFC6BD">small +ve change</span>
    + <span class="larger_smaller_nums" style="background-color: #DBECC1">small -ve change</span> 
    + <span class="larger_smaller_nums" style="background-color: #9CC951">large -ve change</span>
    + A dash "–" in the rate of change column indicates that the previous value was zero so no % change can be calculated.
 - **Sorting** – the table default is that rows are sorted by alcohol-related hospital admissions in descending order. Click on any **column header** to sort by that column in ascending order and click it again to sort in descending order.
 - **Comparisons** – click on the **black triangle** at the start of each row to display more details including:
    + Comparisons in rates relative to Scotland and NHS GGC. The cells for this are coloured to the same scheme as the rate of change columns.
    +	The most recent population of that intermediate zone.
 - **Download Data** – click the Download Data button to export the data shown in the profile into Excel. The data will be all rows in the table, rather than any filtered state that the tables may be in at the point of the download.

<br/>

#### <span style="text-decoration:underline">**IZ Profile**</span>

 - The default table shows all Intermediate Zones (IZs) in NHS GGC.
 - **Filter by HSCP** – the click into the HSCP search box at the top of the page and select an HSCP, multiple values can be selected. Use the backspace key to delete any chosen values. Note that selecting ‘(All)’ in the HSCP search box does not function as it should. To return to the default unfiltered view, delete all values shown in the filter box using the backspace key.
 - **Find an IZ** – click into either search box above the two leftmost columns and type to find a particular IZ by code or name.
 - EASR cells are coloured light orange <span class="highlight_colour" style="background-color: #F3DE90">like this</span> to indicate values that are in the 75^th^ percentile or above for all NHS GGC.
 - Once the data is filtered, a red circle \ <span style="color: #B8100D"> `r shiny::icon("circle-o")` </span> \ will show values that are in the 75th percentile or above for the filtered data. If you filter for a specific HSCP this will help identify outliers within that HSCP.






### Indicator Detail Notes

#### **Alcohol Harms Report**
#### **NHS Greater Glasgow and Clyde**
#### Information for using the 'Hospital Admissions', 'Mental Health Admissions' and 'Deaths' pages

<br/>

These pages contains trends in the alcohol harms indicators by Intermediate Zone (IZ).

Each page copntains  three tabs:

 - **EASR** – the trend in European Age-sex Standardised Rate (EASR) per 10,000 population.
 - **Change from Initial Year** – the rate of change (%) relative to the first time period available.
 - **Year on Year change** – the rate of change (%) relative to the time period immediately before the current one.

<br/>


#### <span style="text-decoration:underline">**Overall**</span>

 - The default table shows all Intermediate Zones (IZs) in NHS GGC.
 - **Filter by HSCP** – click into the HSCP search box at the top of the page and select an HSCP, multiple values can be selected. Use the backspace key to delete any chosen values. Note that selecting ‘(All)’ in the HSCP search box does not function as it should. To return to the default unfiltered view, delete all values shown in the filter box using the backspace key.
 - **Find an IZ** – click into either search box above the two leftmost columns and type to find a particular IZ by code or name.
 - **Sorting** – the table default is that rows are sorted by alcohol-related hospital admissions in descending order. Click on any column header to sort by that column in ascending order and click it again to sort in descending order.
 - **HSCP Table** – below each table showing IZ data, there is a shorter table showing the same data for HSCPs within GGC, GGC total and Scotland total.
 - **Download Data** – click the Download Data button to export the data shown in the profile into Excel. The data will be all rows in the table, rather than any filtered state that the tables may be in at the point of the download. The Excel file will contain six worksheets, an IZ and HSCP relating to each tab.

<br/>


#### <span style="text-decoration:underline">**EASR**</span>

 - EASR cells are coloured light orange <span class="highlight_colour" style="background-color: #F3DE90">like this</span> to indicate values that are in the 75th percentile or above for all NHS GGC 
 - Once the data is filtered, a red circle \ <span style="color: #B8100D"> `r shiny::icon("circle-o")` </span> \ will show values that are in the 75th percentile or above for the filtered data. If you filter for a specific HSCP this will help identify outliers within that HSCP.

<br/>


#### <span style="text-decoration:underline">**Change from Initial Year / Year on Year change**</span>

 - Rate of change (% change) cells are coloured based on the relative positive (+ve) or negative (-ve) values in that column:
    + <span class="larger_smaller_nums" style="background-color: #d26146">large +ve change</span> 
    + <span class="larger_smaller_nums" style="background-color: #EFC6BD">small +ve change</span>
    + <span class="larger_smaller_nums" style="background-color: #DBECC1">small -ve change</span> 
    + <span class="larger_smaller_nums" style="background-color: #9CC951">large -ve change</span>
 - The rate of change for the first year is omitted and displayed as a dash "–" since there is no previous year.
 - In the Change from Initial Year table, if the EASR for the first year has a value of 0, then none of the following years can have a rate of change calculated relative to it and so every entry in that row will have a dash "–".




Profile {data-icon="fa-list"}
=====================================


```{r crosstalk_filter, include=FALSE}
all_table_data <- make_profile_frame(data) %>% arrange(desc(across(contains("hospital admissions"))))

```

row {data-height=34}
--------------------------------------------------

```{r warn_0}
warning_text()
```

row {.tabset}
--------------------------------------------------

```{r profile_setup, include=FALSE}
iz_table <- iz_data(all_table_data)
big_area_table <- big_area_data(all_table_data) %>% arrange(iz %in% big_areas)

shared_table_iz_main <- SharedData$new(iz_table, group="profile_table", key = ~iz)
```



### IZ Profile

<div class = "profile_total_container">
<div class = "filter_button_wrapper">
<div class = "download_button_box">

```{r iz_profile_download_btn}
download_this(
    table_for_download_profile(iz_table),
    output_name = "Alcohol_harms_profile_izs",
    output_extension = ".xlsx",
    button_label = "Download Data",
    button_type = "primary",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
```

</div>
<div class = "filter_select_box">

```{r iz_profile_hscp_selector}
filter_select("auto", "HSCP", shared_table_iz_main, ~hscp, multiple=TRUE)
```

</div>
</div>

<div class = "profile_inner_container">
```{r reactable_display_profile}
profile_table(iz_table, shared_table_iz_main)
```
</div>
</div>

### HSCP Profile

<div class = "filter_button_wrapper">
<div class = "download_button_box">

```{r hscp_profile_download_btn}
download_this(
    table_for_download_profile(big_area_table) %>% 
      rename(area = iz) %>% 
      select(-`iz name`),
    output_name = "Alcohol_harms_profile_hscps",
    output_extension = ".xlsx",
    button_label = "Download Data",
    button_type = "primary",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
```

</div>
</div>

<div class = "profile_inner_container">
```{r reactable_big_area_display_profile}
profile_table(big_area_table, big_area_table, all_default_cols=FALSE)
```
</div>

Hospital Admissions {data-icon="fa-table"}
=====================================


```{r indicator_setup, include=FALSE}
indicators <- c("Alcohol-related hospital admissions",
                "Alcohol-related mental health admissions",
                "Alcohol-specific deaths")

indicator_data <- indicators %>% 
  map(~make_indicator_detail_frames(data = data, indicator_name = .x))

names(indicator_data) <- indicators

# Making shared versions of the indicator data
indicator_data_shared <- indicator_data %>%
  imap(function(data, iname) data %>% map(~ .x %>%
                    # get first (iz not hscp) table
                    .[[1]] %>% 
                    # add sparkline to shared data
                    mutate(sparkline=NA) %>% 
                    SharedData$new( key=~iz, group = iname)))

demo_df_regular <- indicator_data %>% .[[1]] %>% .[[1]]
demo_df_shared <- indicator_data_shared %>% .[[1]] %>% .[[1]]


download_data_names <- c("EASR", "(%) Change Initial", "(%) Change Rolling") %>% 
  rep(each = 2) %>% 
  paste(., c("iz", "hscp") %>% 
          rep(3), sep = "_")


# Helper function that roundsj download data and
# multiplies changes by 100
format_download <- function(data, iname){

    if(grepl("Change", iname)){
      data <- data %>%
        mutate(across(where(is.numeric), function(x) x*100))
    }
    
    data <- data %>%
      mutate(across(where(is.numeric), function(x) round(x, 1)))
}
  

download_data <- indicator_data %>%
  map(~flatten(.x)) %>% 
  map(~set_names(.x, nm = download_data_names)) %>% 
  map(~.x %>%
        imap(~format_download(.x, .y))
  )



# all output (tables and download buttons)
# wrapped up in to lists
output_indicator <- 
  pmap(list(indicators,
            indicator_data,
            indicator_data_shared,
            download_data),
       
       ~ list("download_btn" = download_this(..4,
                                             output_name = ..1,
                                             output_extension = ".xlsx",
                                             button_label = "Download Data",
                                             button_type = "primary",
                                             has_icon = TRUE,
                                             icon = "fa fa-save"),
              
              # --------------------------------------------------------
              
              "vals_table_iz" = indicator_table(..2[["vals"]][["iz"]],
                                                ..3[["vals"]],
                                                type = "val",
                                                sparkline_type = "line"),
              
              "vals_table_hscp" = indicator_table(..2[["vals"]][["hscp"]],
                                                  type = "val",
                                                  sparkline_type = "line",
                                                  all_initial_cols = FALSE,
                                                  is_being_filtered = FALSE),
              
              # --------------------------------------------------------
              
              "change_ini_table_iz" = indicator_table(..2[["change_ini"]][["iz"]],
                                                      ..3[["change_ini"]],
                                                      type = "change",
                                                      ini_or_year_on_year = "ini",
                                                      sparkline_type = "bar"),
              
              "change_ini_table_hscp" = indicator_table(..2[["change_ini"]][["hscp"]],
                                                        type = "change",
                                                        ini_or_year_on_year = "ini",
                                                        sparkline_type = "bar",
                                                        all_initial_cols = FALSE,
                                                        is_being_filtered = FALSE),
              # --------------------------------------------------------
              
              "change_rolling_table_iz" = indicator_table(..2[["change_rolling"]][["iz"]],
                                                          ..3[["change_rolling"]],
                                                          type = "change",
                                                          ini_or_year_on_year = "year_on_year",
                                                          sparkline_type = "bar"),
              
              "change_rolling_table_hscp" = indicator_table(..2[["change_rolling"]][["hscp"]],
                                                            type = "change",
                                                            ini_or_year_on_year = "year_on_year",
                                                            sparkline_type = "bar",
                                                            all_initial_cols = FALSE,
                                                            is_being_filtered = FALSE)
       )
  )


names(output_indicator) <- indicators

```

row {data-height=30}
--------------------------------------------------

<div class = "filter_button_wrapper">
<div class = "download_button_box">
```{r ha_download_btn}
cur_indicator <- "Alcohol-related hospital admissions"

output_indicator[[cur_indicator]] %>% 
  .[["download_btn"]]
```
</div>
<div class = "filter_select_box">
```{r ha_hscp_selector}
filter_select("select_ha", "HSCP", indicator_data_shared[[cur_indicator]][["vals"]], ~hscp, multiple=TRUE)
```
</div>

```{r warn_1}
warning_text()
```

</div>

row {.tabset}
--------------------------------------------------

### EASR

<div class = "indicator_double_table_container">
<div class = "indicator_inner_upper_container">
```{r ha_vals_iz}

output_indicator[[cur_indicator]] %>% 
  .[["vals_table_iz"]]

```
</div>
<div class = "indicator_inner_lower_container">
```{r ha_vals_hscp}
  output_indicator[[cur_indicator]] %>% 
  .[["vals_table_hscp"]]
```
</div>
</div>


### Change from Initial Year

<div class = "indicator_double_table_container">
<div class = "indicator_inner_upper_container">
```{r ha_change_ini_iz}

output_indicator[[cur_indicator]] %>% 
  .[["change_ini_table_iz"]]

```
</div>
<div class = "indicator_inner_lower_container">
```{r ha_change_ini_hscp}

output_indicator[[cur_indicator]] %>% 
  .[["change_ini_table_hscp"]]

```
</div>
</div>

### Year on Year Change

<div class = "indicator_double_table_container">
<div class = "indicator_inner_upper_container">
```{r ha_change_rolling_iz}

output_indicator[[cur_indicator]] %>% 
  .[["change_rolling_table_iz"]]

```
</div>
<div class = "indicator_inner_lower_container">
```{r ha_change_rolling_hscp}

output_indicator[[cur_indicator]] %>% 
  .[["change_rolling_table_hscp"]]

```
</div>
</div>


Mental Health Admissions {data-icon="fa-table"}
=====================================

row {data-height=30}
--------------------------------------------------

<div class = "filter_button_wrapper">
<div class = "download_button_box">
```{r mh_download_btn}
cur_indicator <- "Alcohol-related mental health admissions"

output_indicator[[cur_indicator]] %>% 
  .[["download_btn"]]
```
</div>
<div class = "filter_select_box">
```{r mh_hscp_selector}
filter_select("select_ha", "HSCP", indicator_data_shared[[cur_indicator]][["vals"]], ~hscp, multiple=TRUE)
```
</div>

```{r warn_2}
warning_text()
```


</div>

row {.tabset}
--------------------------------------------------

### EASR

<div class = "indicator_double_table_container">
<div class = "indicator_inner_upper_container">
```{r mh_vals_iz}

 output_indicator[[cur_indicator]] %>% 
   .[["vals_table_iz"]]

```
</div>
<div class = "indicator_inner_lower_container">
```{r mh_vals_hscp}
  output_indicator[[cur_indicator]] %>% 
  .[["vals_table_hscp"]]
```
</div>
</div>


### Change from Initial Year

<div class = "indicator_double_table_container">
<div class = "indicator_inner_upper_container">
```{r mh_change_ini_iz}

output_indicator[[cur_indicator]] %>% 
  .[["change_ini_table_iz"]]

```
</div>
<div class = "indicator_inner_lower_container">
```{r mh_change_ini_hscp}

output_indicator[[cur_indicator]] %>% 
  .[["change_ini_table_iz"]]

```
</div>
</div>


### Year on Year Change


<div class = "indicator_double_table_container">
<div class = "indicator_inner_upper_container">
```{r mh_change_rolling_iz}

output_indicator[[cur_indicator]] %>% 
  .[["change_rolling_table_iz"]]

```
</div>
<div class = "indicator_inner_lower_container">
```{r mh_change_rolling_hscp}

output_indicator[[cur_indicator]] %>% 
  .[["change_rolling_table_iz"]]

```
</div>
</div>


Deaths {data-icon="fa-table"}
=====================================


row {data-height=30}
--------------------------------------------------

<div class = "filter_button_wrapper">
<div class = "download_button_box">
```{r deaths_download_btn}
cur_indicator <- "Alcohol-specific deaths"

output_indicator[[cur_indicator]] %>% 
  .[["download_btn"]]
```
</div>
<div class = "filter_select_box">
```{r deaths_hscp_selector}
filter_select("select_ha", "HSCP", indicator_data_shared[[cur_indicator]][["vals"]], ~hscp, multiple=TRUE)
```
</div>

```{r warn_3}
warning_text()
```

</div>

row {.tabset}
--------------------------------------------------

### EASR


<div class = "indicator_double_table_container">
<div class = "indicator_inner_upper_container">
```{r deaths_vals_iz}

output_indicator[[cur_indicator]] %>% 
  .[["vals_table_iz"]]

```
</div>
<div class = "indicator_inner_lower_container">
```{r deaths_vals_hscp}

output_indicator[[cur_indicator]] %>% 
  .[["vals_table_hscp"]]

```
</div>
</div>



### Change from Initial Year

<div class = "indicator_double_table_container">
<div class = "indicator_inner_upper_container">
```{r deaths_change_ini_iz}

output_indicator[[cur_indicator]] %>% 
  .[["change_ini_table_iz"]]

```
</div>
<div class = "indicator_inner_lower_container">
```{r deaths_change_ini_hscp}

output_indicator[[cur_indicator]] %>% 
  .[["change_ini_table_hscp"]]

```
</div>
</div>



### Year on Year Change

<div class = "indicator_double_table_container">
<div class = "indicator_inner_upper_container">
```{r deaths_change_rolling_iz}

output_indicator[[cur_indicator]] %>% 
  .[["change_rolling_table_iz"]]

```
</div>
<div class = "indicator_inner_lower_container">
```{r deaths_change_rolling_hscp}

output_indicator[[cur_indicator]] %>% 
  .[["change_rolling_table_hscp"]]

```
</div>
</div>

